apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: rabbitmq-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
