apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: "4.4.6"
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: rabbitmq-system
      interval: 24h
