apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: valkey
spec:
  releaseName: valkey
  chart:
    spec:
      chart: valkey
      version: "0.7.2"
      sourceRef:
        kind: HelmRepository
        name: valkey
        namespace: valkey
  interval: 5m
  install:
    remediation:
      retries: 3
