apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  releaseName: topolvm
  chart:
    spec:
      chart: topolvm
      version: "15.7.1"
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: topolvm-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 1
    node:
      lvmdEmbedded: true
    lvmd:
      managed: false
