apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  releaseName: minio-operator
  chart:
    spec:
      chart: operator
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
  interval: 5m
  install:
    remediation:
      retries: 3
