apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: "v1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  interval: 5m
  install:
    remediation:
      retries: 3
