apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: victoria-logs
spec:
  interval: 24h
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.11.15"
      sourceRef:
        kind: HelmRepository
        name: victoria-logs
        namespace: victoria-logs
      interval: 24h
  values:
    vector:
      enabled: true
    server:
      persistentVolume:
        storageClassName: nvme.network-drives.csi.timeweb.cloud
        size: "20Gi"
