apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator
spec:
  releaseName: clickhouse-operator
  interval: 15m
  chart:
    spec:
      chart: altinity-clickhouse-operator
      version: "0.25.3"
      sourceRef:
        kind: HelmRepository
        name: clickhouse-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configs:
      files:
        config.yaml:
          watch:
            namespaces: [".*"]
