apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  releaseName: pgadmin4
  chart:
    spec:
      chart: pgadmin4
      version: "1.50.0"
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    extraConfigmapMounts:
      - name: config-local
        configMap: pgadmin4-config
        subPath: config_local.py
        mountPath: "/pgadmin4/config_local.py"
        readOnly: true
    envVarsFromSecrets:
      - pgadmin4-oauth2-secret
    persistentVolume:
      storageClass: "nvme.network-drives.csi.timeweb.cloud"
      size: "2Gi"
