apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: livekit
  namespace: livekit
spec:
  interval: 24h
  chart:
    spec:
      chart: livekit-server
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository
        name: livekit
        namespace: livekit
      interval: 24h
  values:
    replicaCount: 2
    podHostNetwork: false
    livekit:
      rtc:
        use_external_ip: true
      turn:
        enabled: true
        domain: turn.myhost.com
        tls_port: 7881
        udp_port: 7882
        external_tls: true
      keys:
        myapikey: "myapisecret"
