apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 24h
  chart:
    spec:
      chart: ambient
      version: "1.27.3"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 24h
