apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlas-operator
  namespace: atlas-operator
spec:
  releaseName: atlas-operator
  chart:
    spec:
      chart: atlas-operator
      version: "0.7.13"
      sourceRef:
        kind: HelmRepository
        name: atlas-operator
        namespace: atlas-operator
  interval: 5m
  install:
    remediation:
      retries: 3
