apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: main-minio-tenant 
  namespace: minio-tenant
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  configuration:
    name: storage-configuration
  image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    - name: pool-0
      servers: 2
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: local-path
      volumesPerServer: 2
  users:
    - name: storage-user
