apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: vm-stack
spec:
  interval: 24h
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.58.1"
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: vm-stack
      interval: 24h
