apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
type: Opaque
stringData:
  cookie-secret: "secret"
  client-secret: "secret"
  client-id: "secret"
  dummy-field-to-remove-trailing-whitespace: ""
