apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector-system
spec:
  interval: 24h
  chart:
    spec:
      chart: reflector
      version: "9.1.33"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector-system
      interval: 24h
