apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 24h
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      version: "0.0.31"
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: local-path-storage
      interval: 24h
  values:
    storageClass:
      defaultClass: true
