apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  deployment:
    cluster_wide_access: true
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: http://vmsingle-victoria-metrics-k8s-stack.vm-stack:8428
    grafana:
      external_url: http://victoria-metrics-k8s-stack-grafana.vm-stack:80
      internal_url: http://victoria-metrics-k8s-stack-grafana.vm-stack:80
