apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  interval: 24h
  chart:
    spec:
      chart: kiali-operator
      version: "2.15.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: kiali-operator
      interval: 24h
