apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quickwit
  namespace: quickwit
spec:
  interval: 24h
  chart:
    spec:
      chart: quickwit
      version: "0.7.18"
      sourceRef:
        kind: HelmRepository
        name: quickwit
        namespace: quickwit
      interval: 24h
