apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: valkey
spec:
  releaseName: valkey
  chart:
    spec:
      chart: valkey
      version: "4.0.10"
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: valkey
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    architecture: standalone
    secretAnnotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "my-app"
