apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  releaseName: nats
  interval: 15m
  chart:
    spec:
      chart: nats
      version: "1.3.14"
      sourceRef:
        kind: HelmRepository
        name: nats
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
