apiVersion: v1
kind: Secret
metadata:
  name: postgresql-cluster-user
  namespace: postgresql-cluster
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: appuser
  password: apppassword
