apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: reloader
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
  interval: 5m
  install:
    remediation:
      retries: 3
