apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opensearch-operator
  namespace: opensearch-operator
spec:
  interval: 120m
  url: https://opensearch-project.github.io/opensearch-k8s-operator
