apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch-operator
  namespace: opensearch-operator
spec:
  releaseName: opensearch-operator
  chart:
    spec:
      chart: opensearch-operator
      version: "2.8.0"
      sourceRef:
        kind: HelmRepository
        name: opensearch-operator
        namespace: opensearch-operator
  interval: 5m
  install:
    remediation:
      retries: 3
