apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-helm-charts
  namespace: grafana-system
spec:
  interval: 24h
  url: oci://ghcr.io/grafana/helm-charts
  type: oci
