apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana-system
spec:
  interval: 24h
  chart:
    spec:
      chart: grafana-operator
      version: "v5.20.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-charts
        namespace: grafana-system
      interval: 24h
