apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
